### ISSUE TITLE
glossary

### ISSUE THREAD

**Issue by rishikeshparma** [dtamayo/NCAAbasketball#3]
Please can you add glossary to data file?

**Comment by dtamayo** [comment]
Hah, too long ago to remember! I think you should find enough annotations in this notebook to figure it out if you want: https://github.com/dtamayo/NCAAbasketball/blob/master/GenerateFeatures.ipynb

**Comment by rishikeshparma** [comment]
glossary for the data is required.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by dtamayo** [comment]
Maybe you have the wrong person/repo. This was something I did for fun with some friends a couple years ago...
